using Veldrid.Sdl2;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace Veldrid
{
    /// <summary>
    /// Represents virtual key codes.
    /// </summary>
    public enum VKey
    {
        Unknown = 0,

        Return = '\r',
        Escape = 27,
        Backspace = '\b',
        Tab = '\t',
        Space = ' ',
        Exclamation = '!',
        DoubleQuote = '"',
        Hash = '#',
        Percent = '%',
        Dollar = '$',
        Ampersand = '&',
        Quote = '\'',
        LeftParen = '(',
        RightParen = ')',
        Asterisk = '*',
        Plus = '+',
        Comma = ',',
        Minus = '-',
        Period = '.',
        Slash = '/',
        Num0 = '0',
        Num1 = '1',
        Num2 = '2',
        Num3 = '3',
        Num4 = '4',
        Num5 = '5',
        Num6 = '6',
        Num7 = '7',
        Num8 = '8',
        Num9 = '9',
        Colon = ':',
        Semicolon = ';',
        Less = '<',
        Equals = '=',
        Greater = '>',
        Question = '?',
        At = '@',

        // Skip uppercase letters

        LeftBracket = '[',
        Backslash = '\\',
        RightBracket = ']',
        Caret = '^',
        Underscore = '_',
        Backquote = '`',
        a = 'a',
        b = 'b',
        c = 'c',
        d = 'd',
        e = 'e',
        f = 'f',
        g = 'g',
        h = 'h',
        i = 'i',
        j = 'j',
        k = 'k',
        l = 'l',
        m = 'm',
        n = 'n',
        o = 'o',
        p = 'p',
        q = 'q',
        r = 'r',
        s = 's',
        t = 't',
        u = 'u',
        v = 'v',
        w = 'w',
        x = 'x',
        y = 'y',
        z = 'z',

        CapsLock = SDL_Scancode.SDL_SCANCODE_CAPSLOCK | (1 << 30),

        F1 = SDL_Scancode.SDL_SCANCODE_F1 | (1 << 30),
        F2 = SDL_Scancode.SDL_SCANCODE_F2 | (1 << 30),
        F3 = SDL_Scancode.SDL_SCANCODE_F3 | (1 << 30),
        F4 = SDL_Scancode.SDL_SCANCODE_F4 | (1 << 30),
        F5 = SDL_Scancode.SDL_SCANCODE_F5 | (1 << 30),
        F6 = SDL_Scancode.SDL_SCANCODE_F6 | (1 << 30),
        F7 = SDL_Scancode.SDL_SCANCODE_F7 | (1 << 30),
        F8 = SDL_Scancode.SDL_SCANCODE_F8 | (1 << 30),
        F9 = SDL_Scancode.SDL_SCANCODE_F9 | (1 << 30),
        F10 = SDL_Scancode.SDL_SCANCODE_F10 | (1 << 30),
        F11 = SDL_Scancode.SDL_SCANCODE_F11 | (1 << 30),
        F12 = SDL_Scancode.SDL_SCANCODE_F12 | (1 << 30),

        PrintScreen = SDL_Scancode.SDL_SCANCODE_PRINTSCREEN | (1 << 30),
        ScrollLock = SDL_Scancode.SDL_SCANCODE_SCROLLLOCK | (1 << 30),
        Pause = SDL_Scancode.SDL_SCANCODE_PAUSE | (1 << 30),
        Insert = SDL_Scancode.SDL_SCANCODE_INSERT | (1 << 30),
        Home = SDL_Scancode.SDL_SCANCODE_HOME | (1 << 30),
        PageUp = SDL_Scancode.SDL_SCANCODE_PAGEUP | (1 << 30),
        Delete = 127,
        End = SDL_Scancode.SDL_SCANCODE_END | (1 << 30),
        PageDown = SDL_Scancode.SDL_SCANCODE_PAGEDOWN | (1 << 30),
        Right = SDL_Scancode.SDL_SCANCODE_RIGHT | (1 << 30),
        Left = SDL_Scancode.SDL_SCANCODE_LEFT | (1 << 30),
        Down = SDL_Scancode.SDL_SCANCODE_DOWN | (1 << 30),
        Up = SDL_Scancode.SDL_SCANCODE_UP | (1 << 30),

        NumLockClear = SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR | (1 << 30),
        KeypadDivide = SDL_Scancode.SDL_SCANCODE_KP_DIVIDE | (1 << 30),
        KeypadMultiply = SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY | (1 << 30),
        KeypadMinus = SDL_Scancode.SDL_SCANCODE_KP_MINUS | (1 << 30),
        KeypadPlus = SDL_Scancode.SDL_SCANCODE_KP_PLUS | (1 << 30),
        KeypadEnter = SDL_Scancode.SDL_SCANCODE_KP_ENTER | (1 << 30),
        Keypad1 = SDL_Scancode.SDL_SCANCODE_KP_1 | (1 << 30),
        Keypad2 = SDL_Scancode.SDL_SCANCODE_KP_2 | (1 << 30),
        Keypad3 = SDL_Scancode.SDL_SCANCODE_KP_3 | (1 << 30),
        Keypad4 = SDL_Scancode.SDL_SCANCODE_KP_4 | (1 << 30),
        Keypad5 = SDL_Scancode.SDL_SCANCODE_KP_5 | (1 << 30),
        Keypad6 = SDL_Scancode.SDL_SCANCODE_KP_6 | (1 << 30),
        Keypad7 = SDL_Scancode.SDL_SCANCODE_KP_7 | (1 << 30),
        Keypad8 = SDL_Scancode.SDL_SCANCODE_KP_8 | (1 << 30),
        Keypad9 = SDL_Scancode.SDL_SCANCODE_KP_9 | (1 << 30),
        Keypad0 = SDL_Scancode.SDL_SCANCODE_KP_0 | (1 << 30),
        KeypadPeriod = SDL_Scancode.SDL_SCANCODE_KP_PERIOD | (1 << 30),

        Application = SDL_Scancode.SDL_SCANCODE_APPLICATION | (1 << 30),
        Power = SDL_Scancode.SDL_SCANCODE_POWER | (1 << 30),
        KeypadEquals = SDL_Scancode.SDL_SCANCODE_KP_EQUALS | (1 << 30),
        F13 = SDL_Scancode.SDL_SCANCODE_F13 | (1 << 30),
        F14 = SDL_Scancode.SDL_SCANCODE_F14 | (1 << 30),
        F15 = SDL_Scancode.SDL_SCANCODE_F15 | (1 << 30),
        F16 = SDL_Scancode.SDL_SCANCODE_F16 | (1 << 30),
        F17 = SDL_Scancode.SDL_SCANCODE_F17 | (1 << 30),
        F18 = SDL_Scancode.SDL_SCANCODE_F18 | (1 << 30),
        F19 = SDL_Scancode.SDL_SCANCODE_F19 | (1 << 30),
        F20 = SDL_Scancode.SDL_SCANCODE_F20 | (1 << 30),
        F21 = SDL_Scancode.SDL_SCANCODE_F21 | (1 << 30),
        F22 = SDL_Scancode.SDL_SCANCODE_F22 | (1 << 30),
        F23 = SDL_Scancode.SDL_SCANCODE_F23 | (1 << 30),
        F24 = SDL_Scancode.SDL_SCANCODE_F24 | (1 << 30),
        Execute = SDL_Scancode.SDL_SCANCODE_EXECUTE | (1 << 30),
        Help = SDL_Scancode.SDL_SCANCODE_HELP | (1 << 30),
        Menu = SDL_Scancode.SDL_SCANCODE_MENU | (1 << 30),
        Select = SDL_Scancode.SDL_SCANCODE_SELECT | (1 << 30),
        Stop = SDL_Scancode.SDL_SCANCODE_STOP | (1 << 30),
        Again = SDL_Scancode.SDL_SCANCODE_AGAIN | (1 << 30),
        Undo = SDL_Scancode.SDL_SCANCODE_UNDO | (1 << 30),
        Cut = SDL_Scancode.SDL_SCANCODE_CUT | (1 << 30),
        Copy = SDL_Scancode.SDL_SCANCODE_COPY | (1 << 30),
        Paste = SDL_Scancode.SDL_SCANCODE_PASTE | (1 << 30),
        Find = SDL_Scancode.SDL_SCANCODE_FIND | (1 << 30),
        Mute = SDL_Scancode.SDL_SCANCODE_MUTE | (1 << 30),
        VolumeUp = SDL_Scancode.SDL_SCANCODE_VOLUMEUP | (1 << 30),
        VolumeDown = SDL_Scancode.SDL_SCANCODE_VOLUMEDOWN | (1 << 30),
        KeypadComma = SDL_Scancode.SDL_SCANCODE_KP_COMMA | (1 << 30),
        KeypadEqualsAs400 = SDL_Scancode.SDL_SCANCODE_KP_EQUALSAS400 | (1 << 30),

        AltErase = SDL_Scancode.SDL_SCANCODE_ALTERASE | (1 << 30),
        SysReq = SDL_Scancode.SDL_SCANCODE_SYSREQ | (1 << 30),
        Cancel = SDL_Scancode.SDL_SCANCODE_CANCEL | (1 << 30),
        Clear = SDL_Scancode.SDL_SCANCODE_CLEAR | (1 << 30),
        Prior = SDL_Scancode.SDL_SCANCODE_PRIOR | (1 << 30),
        Return2 = SDL_Scancode.SDL_SCANCODE_RETURN2 | (1 << 30),
        Separator = SDL_Scancode.SDL_SCANCODE_SEPARATOR | (1 << 30),
        Out = SDL_Scancode.SDL_SCANCODE_OUT | (1 << 30),
        Oper = SDL_Scancode.SDL_SCANCODE_OPER | (1 << 30),
        ClearAgain = SDL_Scancode.SDL_SCANCODE_CLEARAGAIN | (1 << 30),
        CrSel = SDL_Scancode.SDL_SCANCODE_CRSEL | (1 << 30),
        ExSel = SDL_Scancode.SDL_SCANCODE_EXSEL | (1 << 30),

        Keypad00 = SDL_Scancode.SDL_SCANCODE_KP_00 | (1 << 30),
        Keypad000 = SDL_Scancode.SDL_SCANCODE_KP_000 | (1 << 30),
        ThousandsSeparator = SDL_Scancode.SDL_SCANCODE_THOUSANDSSEPARATOR | (1 << 30),
        DecimalSeparator = SDL_Scancode.SDL_SCANCODE_DECIMALSEPARATOR | (1 << 30),
        CurrencyUnit = SDL_Scancode.SDL_SCANCODE_CURRENCYUNIT | (1 << 30),
        CurrencySubunit = SDL_Scancode.SDL_SCANCODE_CURRENCYSUBUNIT | (1 << 30),
        KeypadLeftParen = SDL_Scancode.SDL_SCANCODE_KP_LEFTPAREN | (1 << 30),
        KeypadRightParen = SDL_Scancode.SDL_SCANCODE_KP_RIGHTPAREN | (1 << 30),
        KeypadLeftBrace = SDL_Scancode.SDL_SCANCODE_KP_LEFTBRACE | (1 << 30),
        KeypadRightBrace = SDL_Scancode.SDL_SCANCODE_KP_RIGHTBRACE | (1 << 30),
        KeypadTab = SDL_Scancode.SDL_SCANCODE_KP_TAB | (1 << 30),
        KeypadBackspace = SDL_Scancode.SDL_SCANCODE_KP_BACKSPACE | (1 << 30),
        KeypadA = SDL_Scancode.SDL_SCANCODE_KP_A | (1 << 30),
        KeypadB = SDL_Scancode.SDL_SCANCODE_KP_B | (1 << 30),
        KeypadC = SDL_Scancode.SDL_SCANCODE_KP_C | (1 << 30),
        KeypadD = SDL_Scancode.SDL_SCANCODE_KP_D | (1 << 30),
        KeypadE = SDL_Scancode.SDL_SCANCODE_KP_E | (1 << 30),
        KeypadF = SDL_Scancode.SDL_SCANCODE_KP_F | (1 << 30),
        KeypadXor = SDL_Scancode.SDL_SCANCODE_KP_XOR | (1 << 30),
        KeypadPower = SDL_Scancode.SDL_SCANCODE_KP_POWER | (1 << 30),
        KeypadPercent = SDL_Scancode.SDL_SCANCODE_KP_PERCENT | (1 << 30),
        KeypadLess = SDL_Scancode.SDL_SCANCODE_KP_LESS | (1 << 30),
        KeypadGreater = SDL_Scancode.SDL_SCANCODE_KP_GREATER | (1 << 30),
        KeypadAmpersand = SDL_Scancode.SDL_SCANCODE_KP_AMPERSAND | (1 << 30),
        KeypadDoubleAmpersand = SDL_Scancode.SDL_SCANCODE_KP_DBLAMPERSAND | (1 << 30),
        KeypadVerticalBar = SDL_Scancode.SDL_SCANCODE_KP_VERTICALBAR | (1 << 30),
        KeypadDoubleVerticalBar = SDL_Scancode.SDL_SCANCODE_KP_DBLVERTICALBAR | (1 << 30),
        KeypadColon = SDL_Scancode.SDL_SCANCODE_KP_COLON | (1 << 30),
        KeypadHash = SDL_Scancode.SDL_SCANCODE_KP_HASH | (1 << 30),
        KeypadSpace = SDL_Scancode.SDL_SCANCODE_KP_SPACE | (1 << 30),
        KeypadAt = SDL_Scancode.SDL_SCANCODE_KP_AT | (1 << 30),
        KeypadExclamation = SDL_Scancode.SDL_SCANCODE_KP_EXCLAM | (1 << 30),
        KeypadMemoryStore = SDL_Scancode.SDL_SCANCODE_KP_MEMSTORE | (1 << 30),
        KeypadMemoryRecall = SDL_Scancode.SDL_SCANCODE_KP_MEMRECALL | (1 << 30),
        KeypadMemoryClear = SDL_Scancode.SDL_SCANCODE_KP_MEMCLEAR | (1 << 30),
        KeypadMemoryAdd = SDL_Scancode.SDL_SCANCODE_KP_MEMADD | (1 << 30),
        KeypadMemorySubtract = SDL_Scancode.SDL_SCANCODE_KP_MEMSUBTRACT | (1 << 30),
        KeypadMemoryMultiply = SDL_Scancode.SDL_SCANCODE_KP_MEMMULTIPLY | (1 << 30),
        KeypadMemoryDivide = SDL_Scancode.SDL_SCANCODE_KP_MEMDIVIDE | (1 << 30),
        KeypadPlusMinus = SDL_Scancode.SDL_SCANCODE_KP_PLUSMINUS | (1 << 30),
        KeypadClear = SDL_Scancode.SDL_SCANCODE_KP_CLEAR | (1 << 30),
        KeypadClearEntry = SDL_Scancode.SDL_SCANCODE_KP_CLEARENTRY | (1 << 30),
        KeypadBinary = SDL_Scancode.SDL_SCANCODE_KP_BINARY | (1 << 30),
        KeypadOctal = SDL_Scancode.SDL_SCANCODE_KP_OCTAL | (1 << 30),
        KeypadDecimal = SDL_Scancode.SDL_SCANCODE_KP_DECIMAL | (1 << 30),
        KeypadHexadecimal = SDL_Scancode.SDL_SCANCODE_KP_HEXADECIMAL | (1 << 30),

        LeftControl = SDL_Scancode.SDL_SCANCODE_LCTRL | (1 << 30),
        LeftShift = SDL_Scancode.SDL_SCANCODE_LSHIFT | (1 << 30),
        LeftAlt = SDL_Scancode.SDL_SCANCODE_LALT | (1 << 30),
        LeftGui = SDL_Scancode.SDL_SCANCODE_LGUI | (1 << 30),
        RightControl = SDL_Scancode.SDL_SCANCODE_RCTRL | (1 << 30),
        RightShift = SDL_Scancode.SDL_SCANCODE_RSHIFT | (1 << 30),
        RightAlt = SDL_Scancode.SDL_SCANCODE_RALT | (1 << 30),
        RightGui = SDL_Scancode.SDL_SCANCODE_RGUI | (1 << 30),
        Mode = SDL_Scancode.SDL_SCANCODE_MODE | (1 << 30),

        AudioNext = SDL_Scancode.SDL_SCANCODE_AUDIONEXT | (1 << 30),
        AudioPrevios = SDL_Scancode.SDL_SCANCODE_AUDIOPREV | (1 << 30),
        AudioStop = SDL_Scancode.SDL_SCANCODE_AUDIOSTOP | (1 << 30),
        AudioPlay = SDL_Scancode.SDL_SCANCODE_AUDIOPLAY | (1 << 30),
        AudioMute = SDL_Scancode.SDL_SCANCODE_AUDIOMUTE | (1 << 30),
        MediaSelect = SDL_Scancode.SDL_SCANCODE_MEDIASELECT | (1 << 30),
        WWW = SDL_Scancode.SDL_SCANCODE_WWW | (1 << 30),
        Mail = SDL_Scancode.SDL_SCANCODE_MAIL | (1 << 30),
        Calculator = SDL_Scancode.SDL_SCANCODE_CALCULATOR | (1 << 30),
        Computer = SDL_Scancode.SDL_SCANCODE_COMPUTER | (1 << 30),
        AppControlSearch = SDL_Scancode.SDL_SCANCODE_AC_SEARCH | (1 << 30),
        AppControlHome = SDL_Scancode.SDL_SCANCODE_AC_HOME | (1 << 30),
        AppControlBack = SDL_Scancode.SDL_SCANCODE_AC_BACK | (1 << 30),
        AppControlForward = SDL_Scancode.SDL_SCANCODE_AC_FORWARD | (1 << 30),
        AppControlStop = SDL_Scancode.SDL_SCANCODE_AC_STOP | (1 << 30),
        AppControlRefresh = SDL_Scancode.SDL_SCANCODE_AC_REFRESH | (1 << 30),
        AppControlBookmarks = SDL_Scancode.SDL_SCANCODE_AC_BOOKMARKS | (1 << 30),

        BrightnessDown = SDL_Scancode.SDL_SCANCODE_BRIGHTNESSDOWN | (1 << 30),
        BrightnessUp = SDL_Scancode.SDL_SCANCODE_BRIGHTNESSUP | (1 << 30),
        DisplaySwitch = SDL_Scancode.SDL_SCANCODE_DISPLAYSWITCH | (1 << 30),

        KeyboardIlluminationToggle = SDL_Scancode.SDL_SCANCODE_KBDILLUMTOGGLE | (1 << 30),
        KeyboardIlluminationDown = SDL_Scancode.SDL_SCANCODE_KBDILLUMDOWN | (1 << 30),
        KeyboardIlluminationUp = SDL_Scancode.SDL_SCANCODE_KBDILLUMUP | (1 << 30),

        Eject = SDL_Scancode.SDL_SCANCODE_EJECT | (1 << 30),
        Sleep = SDL_Scancode.SDL_SCANCODE_SLEEP | (1 << 30),
    }
}
